name: BACKEND CI/CD

on:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  AWS_REGION: 'ca-central-1'
  FRONTEND_APP_PATH: './frontend'
  BACKEND_APP_PATH: './backend'

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  test-and-deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-get install docker-ce
    - name: Check Docker Version
      run: docker --version

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install cdk dependencies
      run: npm install --frozen-lockfile
      working-directory: ${{ env.BACKEND_APP_PATH }}

    - name: Run backend tests
      run: npm run test
      working-directory: ${{ env.BACKEND_APP_PATH }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ACTIONS_ROLE_GITHUB }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Bootstrap and deploy CDK app
      run: cdk bootstrap && cdk deploy BackendStack --require-approval never
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
      working-directory: ${{ env.BACKEND_APP_PATH }}